services:

  mysql:
    container_name: hipper-mysql
    build: 
      context: ./src/back-end/database
    ports:
      - "3306:3306"
    env_file:
      - ./src/back-end/database/.env
    volumes:
      - ./src/back-end/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u $$MYSQL_ROOT_USER -p$$MYSQL_ROOT_PASSWORD || exit 1"] # ensures a connection can be made before starting flask service
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  flask:
    container_name: hipper-webapp
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./src/back-end/database/.env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=__init__.py
    volumes:
      - ./src/app:/app